spring:
  application.name: LIBRARY-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVICE_URI}
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URI}
  datasource:
    url: ${SPRING_DATASOURCE2_URL}
    username: ${SPRING_DATASOURCE2_USERNAME}
    password: ${SPRING_DATASOURCE2_PASSWORD}

server:
  port: 9892

