spring:
  application.name: SECURITY-SERVICE
  
  docker:
    compose:
      enabled: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Donald
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cloud:
    discovery:
      enabled: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/settings_service
    username: postgres
    password: donald
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
server:
  port: 9891
  
jwt:
  auth:
    converter:
      ressource-id: book-rest-api
      pricipal-attribute: prefered_username