spring:
  application:
    name:
      REACTIVE-GATEWAY
  cloud:
    discovery:
      enabled: true
    config:
      uri: ${CONFIG_SERVICE_URI}

  config:
    import: optional:configserver:${CONFIG_SERVICE_URI}

server:
  port: 9898


