spring:
  application:
    name:
      REACTIVE-GATEWAY
  cloud:
    discovery:
      enabled: true
server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

